name: flutter_navigator
description: turn by tun navigator
version: 0.1.0+1


environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  json: ^0.20.2
  maplibre_gl: ^0.20.0
  flutter_tts: ^4.0.2
  expandable_bottom_sheet: ^1.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ">=6.0.0 <8.0.0"
